name: pull-request-build
run-name: "#${{ github.event.pull_request.number}} ${{ github.event.pull_request.title}}"
on:
  pull_request:
    types: [ 'opened', 'reopened', 'synchronize' ]
jobs:
  build-app:
    runs-on: "ubuntu-latest"
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      # Preparation

      - name: Install screenshot test dependencies
        run: "sudo apt-get install -y libfreetype6 fontconfig fonts-dejavu"
      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
      - name: Install pebble SDK
        run: "uv tool install pebble-tool && pebble sdk install latest"
      - name: Globally enable build cache and parallel execution
        run: |
          mkdir -p ~/.gradle
          
          cat >> ~/.gradle/gradle.properties<< EOF
          org.gradle.caching=true
          org.gradle.parallel=true
          EOF
      - name: Force all tasks to be rerun when debug mode is on
        # This allows us to force rerun the build if cache has gotten corrupted
        run: 'if [[ "${{ runner.debug }}" == "1" ]]; then
                  echo "GLOBAL_FLAGS= --rerun-tasks" >> "$GITHUB_ENV";
              else
                  echo "GLOBAL_FLAGS=" >> "$GITHUB_ENV";
              fi
            '
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          lfs: true
          submodules: recursive
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
        with:
          java-version: '21'
          distribution: temurin
          cache: gradle
      - uses: android-actions/setup-android@7c5672355aaa8fde5f97a91aa9a99616d1ace6bc
      - run: sdkmanager "platforms;android-33" "platforms;android-34"
      - name: Enable Gradle remote build cache
        uses: burrunan/gradle-cache-action@663fbad34e03c8f12b27f4999ac46e3d90f87eca
        with:
          debug: false
          concurrent: true
          read-only: true
          build-root-directory: mobile

      # Build mobile app

      - name: Compile app
        run: "./gradlew compileReleaseKotlin assembleDebug"
        working-directory: mobile

      # Tests

      - name: Compile Unit Tests
        run: "./gradlew compileDebugUnitTestSources compileReleaseUnitTestSources"
        working-directory: mobile
      - name: Lint
        run: "./gradlew lintRelease runDebugDetekt assertModuleGraph buildHealth detectTooManyFiles :bucketsync:data:verifyDebugDatabaseMigration reportMerge --continue"
        working-directory: mobile
      - name: Double check DB with the generated schema
        run: "./gradlew :bucketsync:data:generateDebugDatabaseSchema :bucketsync:data:verifyDebugDatabaseMigration --continue"
        working-directory: mobile
      - name: Run Unit Tests
        run: "./gradlew runDebugTests -x :app-screenshot-tests:testDebugUnitTest --continue"
        working-directory: mobile
      - name: "Generate new Screenshot Tests"
        run: "config/generate-screenshots.sh ${{ github.event.pull_request.head.ref }}"
        working-directory: mobile
      - name: "Run Screenshot Tests"
        run: "./gradlew --continue verifyPaparazziDebug"
        working-directory: mobile
      - name: "Create jacoco aggregate"
        run: "./gradlew aggregatedJacocoReport"
        working-directory: mobile

      # Build watchapp

      - name: Build watchapp
        run: pebble build
        working-directory: watch

        #     GitHub Actions does not allow PR actions triggered from external contributors
        #     to post comments. As a workaround, we upload metadata artifacts
        #     and then sarif-comment.yaml workflow will run, which will post the comment

      - run: echo ${{ github.event.number }} > pr_number.txt
        if: (!cancelled())
      - name: Upload Results
        if: (!cancelled())
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f #v6
        with:
          name: results
          path: |
            **/build/outputs/*-results/**/*.xml
            **/build/*-results/**/*.xml
            pr_number.txt
            ${{ github.event_path }}
            mobile/merge.sarif
            mobile/build/reports/jacoco/aggregatedJacocoReport/aggregatedJacocoReport.xml
      - name: "Upload Screenshot test failures"
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f #v6
        if: failure()
        with:
          name: failed-screenshot-tests
          path: mobile/app-screenshot-tests/build/paparazzi/failures
